### PR TITLE
fix(besside-ng): bad beacon error

### LINKED ISSUE #2203: Incorrect work of Besside-ng. Error: Bad Beacon
OS: Kali Linux Arm64 (last update)
DEV: Raspberry Pi 4
WiFi adapter: RTL 8812au
Aircrack-ng: Ver. 1.6

For a long time, Besside-ng worked perfectly on this system.

But recently, the program has completely stopped working correctly.

Outputs this to the terminal:

```
[17:51:12] / Scanning chan 04
Bad beacon
[17:51:12] - Scanning chan 05
Bad beacon
[17:51:12] | Scanning chan 05
Bad beacon
[17:51:12] - Scanning chan 06
Bad beacon
[17:51:12] - Scanning chan 06
Bad beacon
[17:51:12] | Scanning chan 07
Bad beacon
[17:51:13] / Scanning chan 07
Bad beacon
[17:51:13] - Scanning chan 07
Bad beacon
[17:51:13] | Scanning chan 08
Bad beacon
[17:51:13] / Scanning chan 08
```
What could be the problem?
#besside-ng

### LINKED ISSUE #2268: Besside-ng 1.6 beacon issue
Besside-ng in Aircrack-ng version 1.6 has problem - send bad beacon, previous version (1.5.2-3) hasn't the problem

## System Information
OS: Debian 11 Bullseye

### PR DESCRIPTION
**Pull request by ParadoxInfinite**
The initial value for buf was `2048` in https://github.com/aircrack-ng/aircrack-ng/blob/8e552786d117d15b116a9a492fedc3d4286e0330/src/besside-ng/besside-ng.c#L2612
However, in b8828cbc1e5a94b96bdf044ed944065ffec8ca21, it was changed to https://github.com/aircrack-ng/aircrack-ng/blob/b8828cbc1e5a94b96bdf044ed944065ffec8ca21/src/besside-ng/besside-ng.c#L2606

This causes the check `if (totlen < l) goto __bad;` in line 1848 of `besside-ng.c` become true as `totlen` is derived from the `sizeof(*wh)`, which in turn is dependent on `buf`.

The size of `ieee80211_frame` is 24, so 24 * 32 still only results in 768, not 2048. I've tested this to be working with * 16 as well, but as a tradeoff between future possibility and memory conservation, I settled on 32. 

Let me know if I should increase/decrease the value.

---
#### Fixes: https://github.com/aircrack-ng/aircrack-ng/issues/2203

### CODE REVIEW

**Comment by ParadoxInfinite** [comment]
@aircrack-ng Hey, sorry for the ping, but could you take a look at this please? I think there are a couple of other places where the memory allocation could be lower(causing bad beacon issue, but this is the major one), I'll update them as well if this looks good. What do you think would be the right value?

**Comment by 4c1d1c4** [comment]
Hey, not sure if I am right here with this, but I cloned the master branch and changed line 2613 to 

"unsigned char buf[sizeof(struct ieee80211_frame) * 32]; "

just using 32 instead of 8 like mentioned above. The bad beacon error was blown away like in "aircrack-ng_1.5.2-3+b1_arm64.deb". I don't know why (I am not good with c language on this level) I just read that above and tried it out. But now I am getting a "wifi_read: network down" error. I think I will open a discussion for this (did not find it yet). Thx for this here, quite interesting.

**Comment by ParadoxInfinite** [comment]
@jbenden could you have a look at this maybe? It's a 1 line change but would save some issues being raised about bad beacon. I will rebase to the current master branch and also make changes if needed. Let me know, thanks!

**Comment by d3k4-k3rb3r0s** [comment]
Still having this issue, June 2023, edited the besside-ng.c file manually even, fresh install.. nothing

**Pull request merged**
