### PR TITLE
Fix a double-free problem of dev->iwpriv

### PR DESCRIPTION
**Pull request by RafaelLeeImg**
Details are described in:
#2154

### CODE REVIEW

**Comment by dmfreemon** [comment]
See #2094 (from November 2019)

**Comment by RafaelLeeImg** [comment]
Thanks.
I saw that, actually the pointer not referring to a static array.
The free of iwpriv is required. It is not pointing to the element of the static array.

```C
// aircrack-ng/lib/osdep/linux.c, line 1869
iwpriv = wiToolsPath("iwpriv");


// aircrack-ng/lib/osdep/linux.c, line 255
static char * wiToolsPath(const char * tool)
{
    static const char * paths[] = {"/sbin",
                                   ...};
    for (i = 0; i < nbelems; i++)
    {
        path = searchInside(paths[i], tool);
        if (path != NULL) return path;
    }
}


// aircrack-ng/lib/osdep/linux.c, line 194
static char * searchInside(const char * dir, const char * filename)
{
    ...
    curfile = (char *) calloc(1, lentot);

    while (searching)
    {
        if (match)
        {
            // not freed here
            return curfile;
        }
    }

    (void) closedir(dp);
    // free only if curfile not return
    free(curfile);
    ...
}
```

**Comment by dmfreemon** [comment]
> I saw that, actually the pointer not referring to a static array.

Looking at PR #2094 , there is a comment at the top of the wiToolsPath function in linux.c that says:  "Note: The returned string is a new allocation from the heap."

I believe you may be referring to a comment from someone else.

> The free of iwpriv is required.

Are you sure that do_free() via linux_close..() doesn't take care of that free (after PR #2094 is applied)?

**Comment by RafaelLeeImg** [comment]
The code I wrote above is only pseudo code describing the work flow, not from any file from project.
I checked #2094 , the way @dmfreemon deals with device pointer is consistent.
I think if that PR merges, the problem will be solved in a systematic method. Then my PR should be invalid and not required.
I will spend more time checking #2094

**Comment by RafaelLeeImg** [comment]
Same to #2094

**Pull request closed without merging**
