### PR TITLE
workflows: add workflow for building with PCRE, update existing ones from PCRE to PCRE2

### LINKED ISSUE #2394: Update GitHub CI to build with both PCRE1 and PCRE2
# Description

Create a separate CI to build with PCRE1 and 2 with just Ubuntu 20.04, and 22.04 (no tests).

### PR DESCRIPTION
**Pull request by gemesa**
Fixes #2394 

I copied _linux.yml_, renamed it to _linux-pcre.yml_ and deleted the testing part from both ubuntu_22_04 and ubuntu_20_04:
```
echo "::group::run tests"
make -j ${CPUS} check || { find . -name 'test-suite.log' -exec cat {} ';' && exit 1; }
echo "::endgroup::"
``` 

Then looked for relevant files with `grep` and modified them as necessary:
```
┌───(gemesa♾fedora)-[~/git-repos/aircrack-ng-sync]
└─$ grep -rni . -e 'linux.yml'                                           
grep: ./.git/objects/pack/pack-32e8f5b1cfd01ab05227454094b6141c8610a124.pack: binary file matches
grep: ./.git/index: binary file matches
./.github/workflows/linux.yml:59:          key: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/linux.yml') }}
./.github/workflows/linux.yml:178:          key: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/linux.yml') }}
./.github/workflows/style.yml:17:      - '.github/workflows/linux.yml'
./.github/workflows/style.yml:47:      - '.github/workflows/linux.yml'
./.github/workflows/docker.yml:12:      - '.github/workflows/linux.yml'
./INSTALLING:414:- Linux CI (GitHub actions): https://github.com/aircrack-ng/aircrack-ng/actions/workflows/linux.yml
./README.md:20:[![Linux CI](https://github.com/aircrack-ng/aircrack-ng/actions/workflows/linux.yml/badge.svg?event=push)](https://github.com/aircrack-ng/aircrack-ng/actions/workflows/linux.yml)
./README.md:484:- Linux CI (GitHub actions): https://github.com/aircrack-ng/aircrack-ng/actions/workflows/linux.yml
```

I also updated the existing workflows from PCRE to PCRE2.

### CODE REVIEW

**Comment by Mister-X-** [comment]
Let's limit the `linux-pcre` CI even more: using the default clang/gcc compiler on Ubuntu 20.04 and 22.04, and with just OpenSSL. Could you update the file paths to ignore more files (see for example the `style.yml`.

**Comment by gemesa** [comment]
Updated _linux-pcre.yml_, please check it.

**Comment by gemesa** [comment]
Fixed a typo in the commit message.

**Comment by Mister-X-** [comment]
The "Ubuntu 22.04 clang using OpenSSL" failed:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libopencl-clang-12-dev : Conflicts: libopencl-clang-x.y-dev
 libopencl-clang-dev : Conflicts: libopencl-clang-x.y-dev
 python3-clang-11 : Conflicts: python-clang-x.y
 python3-clang-12 : Conflicts: python-clang-x.y
 python3-clang-13 : Conflicts: python-clang-x.y
 python3-clang-14 : Conflicts: python-clang-x.y
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

**Comment by gemesa** [comment]
Fixed.

**Comment by Mister-X-** [comment]
One thing before merging, could you remove the "Archive artifacts" for both CI jobs.

**Comment by gemesa** [comment]
Archiving removed.

**Pull request merged**
