### PR TITLE
add test for hccapx and fix bad c_avl_destoy in this case

### PR DESCRIPTION
**Pull request by ChrisLundquist**

### CODE REVIEW

**Comment by ChrisLundquist** [comment]
```
The command "./build/travis-format.sh OpenSSL "Building with OpenSSL..." ./build/openssl.sh" exited with 1.
0.13s$ ./build/travis-format.sh Dist "Creating a dist tarball and then building from it..." ./build/dist_check.sh
Dist
\e[0K\e[33;1mCreating a dist tarball and then building from it...\e[0m
0.08s+'[' osx == osx ']'
+exit 0
```
I'm missing something here for Travis. It looks like parts have been disabled for osx.
I don't see how `exit 0` returns exist code 1
`+exit 0` -> `exited with 1.`

**Comment by aircrack-ng** [comment]
The way it is displayed is misleading and it's the above one you have to look at. It failed `test-aircrack-ng-0001.sh`

**Comment by aircrack-ng** [comment]
There is a typo in the file extension. Could you also rename it to `StayAlfred.hccapx` and remove the commented out line in the test?

**Comment by ChrisLundquist** [comment]
Looks like the travis ci tests got re-run and passed?

> Could you also rename it to `StayAlfred.hccapx` and remove the commented out line in the test?

done!

**Comment by aircrack-ng** [comment]
Correct, testing it multiple times outside travis was successful, so probably a fluke

**Pull request merged**
