### PR TITLE
Python3 support with 2to3 to all .py files

### PR DESCRIPTION
**Pull request by samueloph**
Just executed python's 2to3 script on all of the .py files and changed the shebang,
this is the first iteration for python3 support of aircrack-ng, there's a chance no
other changes will be required, but this PR needs to be properly tested and reviewed
before merging it.

### CODE REVIEW

**Comment by aircrack-ng** [comment]
Thank you for pointing all the files. 2to3 is good at giving pointers how to fix it.

However, for anybody else using it, it has bugs with print duplicating parenthesis, and not handling imports when there is an if checking for python3, and finally, changing the env to python3, which is going to be taken care of by packager, depending on what the distro chooses. In the case of dcrack, using python3 used chunked encoding when doing POST, and the library didn't support it, so had to add support for that manually.

Commits: 7a944eebab6ebfac1eb8edafdd4c86539fca05b2, bf215097579b45bf34f9545f000dd9fe0211d7b0, 1c0e33edb1dd14e0381c099309f31ed3f6093c79, 8df899c9104583e11b36fac0cb40f28bb26668a0, 52e0db23a0788ba2d199fb9d0fa98b169bbd1cef, 1eba2a4931a8b6b778fab04ad26c9cb594c90403 and f7f4b397f6f99fcbd09731e40e101f316d80fad3

**Comment by samueloph** [comment]
@aircrack-ng thank you for the details on the changes made, I appreciate it.

Are there plans of making a new release? We could package a git snapshot for Debian/Kali to switch to python3 but having a proper upstream release is better, the last one seem to have happened December last year.

Regards,

**Comment by aircrack-ng** [comment]
Yes, very soon

**Comment by rhertzog** [comment]
Thanks for your work! How soon is very soon? In Debian, we have a deadline in two weeks. If the release is not going to happen in the next week, I'd rather package a git snapshot to avoid a temporary removal from Debian testing. See https://tracker.debian.org/pkg/aircrack-ng for details.

**Comment by aircrack-ng** [comment]
It will happen within a week.

**Comment by aircrack-ng** [comment]
1.6 was finally released today

**Comment by samueloph** [comment]
that' s great news, I already did the very initial packaging work, we should have it up-to-date in debian/kali repos soon

**Comment by kimocoder** [comment]
Just don't thrust the 2to3(-3.8) to it's fully.. it's far for flawless that one. And congratulations with a new release, can't wait to look into it!

**Comment by kimocoder** [comment]
@samueloph have to admit I cheated there..
I need to see right away if it plays nice with wifite2 :100: 
https://packages.aircrack-ng.org/artifacts/aircrack-ng/stable/1.6/deb/

**Comment by aircrack-ng** [comment]
2to3 is not perfect, but it's a good way to start, then make adjustments from its modifications; it's easy to see what it changed when using source control. That's how this was done.

**Pull request closed without merging**
