### PR TITLE
Increased CPU scaling slightly (thanks Intel VTune.)

### PR DESCRIPTION
**Pull request by jbenden**

### CODE REVIEW

**Review by Mister-X- — COMMENTED** [review]
It still works but not really seeing any performance boost when running benchmark (testing alternatively master and this PR multiple time). Sometimes, master is above, sometimes this is higher. It is probably due to automatic frequency scaling.

**Comment by jbenden** [comment]
On less than 8 CPUs, it's about the same; like you've shown. However; with >= 8 CPUs, it's better.

**Comment by jbenden** [comment]
Still optimizing, too... Will post benchmark updates...

**Comment by jbenden** [comment]
New benchmark data, for these changes applied. It should be noted that the x86_64 has 4 CPUs, with HT enabled to get 8 available - so a perf. drop isn't completely unexpected at 8 CPUs.

```
x86_64,generic,1,1285
x86_64,generic,2,2539
x86_64,generic,4,4385
x86_64,generic,8,3401
x86_64,sse2,1,1427
x86_64,sse2,2,2637
x86_64,sse2,4,4242
x86_64,sse2,8,5541
x86_64,avx2,1,3550
x86_64,avx2,2,6698
x86_64,avx2,4,12788
x86_64,avx2,8,10380
ppc64le,generic,1,279
ppc64le,generic,2,310
ppc64le,generic,4,718
ppc64le,generic,8,1696
ppc64le,generic,16,2477
ppc64le,generic,32,2243
ppc64le,generic,64,5865
ppc64le,generic,128,6370
ppc64le,altivec,1,268
ppc64le,altivec,2,434
ppc64le,altivec,4,899
ppc64le,altivec,8,1652
ppc64le,altivec,16,2267
ppc64le,altivec,32,1976
ppc64le,altivec,64,3724
ppc64le,altivec,128,4297
ppc64le,power8,1,282
ppc64le,power8,2,451
ppc64le,power8,4,972
ppc64le,power8,8,1870
ppc64le,power8,16,2105
ppc64le,power8,32,2244
ppc64le,power8,64,3464
ppc64le,power8,128,3958
aarch64,generic,1,70
aarch64,generic,2,135
aarch64,generic,4,263
aarch64,generic,8,457
aarch64,neon,1,71
aarch64,neon,2,136
aarch64,neon,4,244
aarch64,neon,8,465
aarch64,asimd,1,70
aarch64,asimd,2,136
aarch64,asimd,4,258
aarch64,asimd,8,463
```

x86_64 machine specs:
```
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
stepping	: 9
microcode	: 0x84
cpu MHz		: 1000.029
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti retpoline intel_pt rsb_ctxsw spec_ctrl tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 7200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
```

ppc64le machine specs:
```
cpu		: POWER8E (raw), altivec supported
clock		: 2061.000000MHz
revision	: 2.1 (pvr 004b 0201)

timebase	: 512000000
platform	: PowerNV
model		: 8247-22L
machine		: PowerNV 8247-22L
firmware	: OPAL v3
```

aarch64 machine specs:
```
BogoMIPS	: 100.00
Features	: fp asimd evtstrm 
CPU implementer	: 0x50
CPU architecture: AArch64
CPU variant	: 0x0
CPU part	: 0x000
CPU revision	: 1

Hardware	: APM X-Gene Mustang board
```

Prior to these changes, it seemed to taper at 4-8 CPUs. With these changes, it now tapers around 16 CPUs.

-Joe

**Pull request closed without merging**
