### PR TITLE
Reworked how both Svn and Git versioning are formatted.

### PR DESCRIPTION
**Pull request by jbenden**
Added support for formatting both Svn and Git versioning information.

### CODE REVIEW

**Comment by aircrack-ng** [comment]
It fails compiling when there is no source control used such as when doing svn export.

**Comment by jbenden** [comment]
I had added an "unknown" for that case in #e15a4a5. Does it still? What's the export command, so I can locally test and fix?

**Comment by jbenden** [comment]
Nevermind, I reproduced the problem.

**Comment by jbenden** [comment]
Fixed.

**Pull request merged**
