### PR TITLE
airodump-ng: bug fix colorize option

### PR DESCRIPTION
**Pull request by scorpius**

### CODE REVIEW

**Comment by aircrack-ng** [comment]
Could you give more details: when it happens and how to reproduce the bug

**Comment by scorpius** [comment]
If you activate the feature by pressing the o key, all clients have the same color. But with the fix, each client matches the color of the AP it is associated to.

**Comment by aircrack-ng** [comment]
With this patch, existing clients not linked to AP in the top section. This is most likely due to a bug in the auto-coloring - See #2019

**Comment by aircrack-ng** [comment]
With this patch, existing clients not linked to AP in the top section become hidden when hitting 'o'. This could be due to a bug in the auto-coloring - See #2019

**Comment by scorpius** [comment]
On my system the non-linked-to-ap clients are visible and have a grey color. I think it is not a bug, but different terminal colors can make it look hidden.

**Pull request closed without merging**
