### PR TITLE
Minor updates on airgraph-ng

### PR DESCRIPTION
**Pull request by cdeletre**
Hi,

I've done few changes for my needs in airgraph-ng like adding `-d` option to keep the dot file and also a "smarter" output file auto-naming. In the same time I've also switched the script to use the library argparse instead of optparse. Maybe it can be useful to the community, I let you decide.

Cyril

### CODE REVIEW

**Comment by aircrack-ng** [comment]
Looks good. One detail: could you remove the README.md change?

**Comment by cdeletre** [comment]
> Looks good. One detail: could you remove the README.md change?

Hi

Thank for accepting my update. Do you need **me** to remove the `README.md` changes ? If so, how do I do ? Sorry about these stupid questions, I don't pull a lot ;)

**Comment by aircrack-ng** [comment]
Commit the change in your master branch.

**Comment by cdeletre** [comment]
> Commit the change in your master branch.

Ok, I got it now :)

**Pull request merged**
