### PR TITLE
Clundquist/fix memory

### PR DESCRIPTION
**Pull request by ChrisLundquist**
98149c9 fixes https://github.com/aircrack-ng/aircrack-ng/pull/1923#issuecomment-406014897

6a52a78 is for extra credit.

### CODE REVIEW

**Comment by ChrisLundquist** [comment]
FWIW: valgrind says there are **no** memory leaks **without** these changes. We do get an overlapping memcpy warning though. (on master and with these changes)

I paused for a moment to think of *why* `98149c9` would "fix" the leak and I am at a loss.
The only thing i could think of would be `st_cur` holds a temporary value that still needs to be cleaned.
That doesn't appear to be the case though since mallocs == frees.

```
$ valgrind --leak-check=full --show-leak-kinds=all  ./src/airdecap-ng -e <redacted>  -p <redacted> /srv/wifi/home-02.pcapdump
==9213== Memcheck, a memory error detector
==9213== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==9213== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==9213== Command: ./src/airdecap-ng -e <redacted> -p <redacted> /srv/wifi/home-02.pcapdump
==9213== 
==9213== Source and destination overlap in memcpy_chk(0x33890c, 0x338920, 50)
==9213==    at 0x4C37660: __memcpy_chk (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9213==    by 0x109B3F: write_packet (in /home/clundquist/aircrack-ng/src/airdecap-ng)
==9213==    by 0x10ADBA: main (in /home/clundquist/aircrack-ng/src/airdecap-ng)
==9213== 
Total number of stations seen         1277
Total number of packets read      19740955
Total number of WEP data packets       654
Total number of WPA data packets   4438627
Number of plaintext data packets      7871
Number of decrypted WEP  packets         0
Number of corrupted WEP  packets         0
Number of decrypted WPA  packets        24
Number of bad TKIP (WPA) packets         0
Number of bad CCMP (WPA) packets       176
==9213== 
==9213== HEAP SUMMARY:
==9213==     in use at exit: 0 bytes in 0 blocks
==9213==   total heap usage: 51,679 allocs, 51,679 frees, 5,062,764 bytes allocated
==9213== 
==9213== All heap blocks were freed -- no leaks are possible
==9213== 
==9213== For counts of detected and suppressed errors, rerun with: -v
==9213== ERROR SUMMARY: 24 errors from 1 contexts (suppressed: 0 from 0)
clundquist@nuc:~/aircrack-ng$ git log
commit 3d02ecb26e7b6653d83b87e0ea197a255137ce94 (HEAD -> master, origin/master, origin/HEAD)
```

**Comment by ChrisLundquist** [comment]
Looks like the overlap error is ~fine.
```
==13047== WARNING: new redirection conflicts with existing -- ignoring it
--13047--     old: 0x05661ac0 (__memcpy_chk_avx_una) R-> (2030.0) 0x04c375e0 __memcpy_chk
--13047--     new: 0x05661ac0 (__memcpy_chk_avx_una) R-> (2024.0) 0x04c36fa0 __memmove_chk
```
we're using memmove there as appropriate, but valgrind was treating it as memcpy.

**Comment by jbenden** [comment]
Thank you! Feel free to merge with these fixes. :+1: 

On an aside, no one tool is completely correct. Valgrind reporting no errors is not actually indicative of "correct"ness. It's annoying, I know. Thank you for your efforts!

**Comment by ChrisLundquist** [comment]
> no one tool is completely correct

For sure. In school we had to test C++99 against borland, visual studios, and gcc because no one implementation was completely correct.

I mean I didn't "see" how the leak was occurring, and was somewhat perplexed that using a different variable fixed it. I could only come up with "maybe casting, maybe st_cur has a dangling malloc..., maybe..." but none of those seemed to hold up.

I don't think I have merge powers.

**Pull request merged**
