### PR TITLE
[airdecap] Speed up airdecap

### PR DESCRIPTION
**Pull request by ChrisLundquist**
Using a tree to find our stations will make this packets * log(stations) time instead of packets * stations

```
$ ls -lah /srv/wifi/Kismet-20180704-11-52-58-1.pcapdump
 7.8G Jul  9 13:44 /srv/wifi/Kismet-20180704-11-52-58-1.pcapdump
```

Existing master:
```
$ time ./airdecap-ng -p <redacted> -e <redacted>  /srv/wifi/Kismet-20180704-11-52-58-1.pcapdump
Total number of packets read      31514113
# ...

real	1m3.403s
user	1m1.866s
sys	0m1.536s
```

This Branch:
```
$ time ./airdecap-ng -p <redacted> -e <redacted>  /srv/wifi/Kismet-20180704-11-52-58-1.pcapdump
Total number of packets read      31505034
# ...

real	0m24.520s
user	0m23.263s
sys	0m1.256s
```

This borrows an AVL tree implementation from collectd which is far more suited for searching than our previous linked list implementation. Changing the station lookup complexity to O(log(n)) from O(n).

For context this was ran on a nuc6i7kyk which is basically a fast laptop.

### CODE REVIEW

**Comment by ChrisLundquist** [comment]
tests are flaking for various unrelated reasons. one was a fork failure, another was failing to download things.

**Comment by aircrack-ng** [comment]
Tests will be checked manually and re-run before merging if needed, don't worry about AppVeyor for now.

**Comment by aircrack-ng** [comment]
Looks good so far. Don't forget to address the remarks in e4426d41ee6ffde4067dbb1e864a9cd2757ae0f0

**Comment by ChrisLundquist** [comment]
Oh I missed those comments. For some reason they didn't email or show up https://github.com/aircrack-ng/aircrack-ng/pull/1923/files

**Comment by ChrisLundquist** [comment]
Done

**Comment by jbenden** [comment]
Please fix your memory leaks.

```
======================================================
   aircrack-ng 1.3_rev-dc38b01: test/test-suite.log
======================================================

# TOTAL: 14
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-airdecap-ng-0001.sh
==============================

=================================================================
==25208==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffd22f1ef0 at pc 0x000000528893 bp 0x7fffd22f1dd0 sp 0x7fffd22f1dc8
WRITE of size 8 at 0x7fffd22f1ef0 thread T0
    #0 0x528892 in c_avl_pick /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8
    #1 0x51493e in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:1056:9
    #2 0x7f22cfcd082f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #3 0x41a218 in _start (/home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng+0x41a218)

Address 0x7fffd22f1ef0 is located in stack of thread T0 at offset 240 in frame
    #0 0x5112ef in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:211

  This frame has 9 object(s):
    [32, 160) 'buf' (line 214)
    [192, 196) 'n' (line 217)
    [208, 214) 'bssid' (line 220)
    [240, 246) 'stmac' (line 220) <== Memory access at offset 240 partially overflows this variable
    [272, 280) 'st_cur' (line 223)
    [304, 328) 'pfh' (line 224)
    [368, 384) 'pkh' (line 225)
    [400, 404) 'option_index' (line 240)
    [416, 480) 'K' (line 852)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8 in c_avl_pick
Shadow bytes around the buggy address:
  0x10007a456380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007a456390: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007a4563a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007a4563b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007a4563c0: f1 f1 f1 f1 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007a4563d0: 00 00 00 00 f2 f2 f2 f2 04 f2 06 f2 f2 f2[06]f2
  0x10007a4563e0: f2 f2 00 f2 f2 f2 00 00 00 f2 f2 f2 f2 f2 00 00
  0x10007a4563f0: f2 f2 f8 f2 f8 f8 f8 f8 f8 f8 f8 f8 f3 f3 f3 f3
  0x10007a456400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007a456410: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007a456420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==25208==ABORTING
FAIL test-airdecap-ng-0001.sh (exit status: 1)

FAIL: test-airdecap-ng-0002.sh
==============================

=================================================================
==25224==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc3844f590 at pc 0x000000528893 bp 0x7ffc3844f470 sp 0x7ffc3844f468
WRITE of size 8 at 0x7ffc3844f590 thread T0
    #0 0x528892 in c_avl_pick /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8
    #1 0x51493e in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:1056:9
    #2 0x7f4c1be7d82f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #3 0x41a218 in _start (/home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng+0x41a218)

Address 0x7ffc3844f590 is located in stack of thread T0 at offset 240 in frame
    #0 0x5112ef in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:211

  This frame has 9 object(s):
    [32, 160) 'buf' (line 214)
    [192, 196) 'n' (line 217)
    [208, 214) 'bssid' (line 220)
    [240, 246) 'stmac' (line 220) <== Memory access at offset 240 partially overflows this variable
    [272, 280) 'st_cur' (line 223)
    [304, 328) 'pfh' (line 224)
    [368, 384) 'pkh' (line 225)
    [400, 404) 'option_index' (line 240)
    [416, 480) 'K' (line 852)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8 in c_avl_pick
Shadow bytes around the buggy address:
  0x100007081e60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100007081e70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100007081e80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100007081e90: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 00 00 00 00
  0x100007081ea0: 00 00 00 00 00 00 00 00 f2 f2 f2 f2 04 f2 06 f2
=>0x100007081eb0: f2 f2[06]f2 f2 f2 00 f2 f2 f2 00 00 00 f2 f2 f2
  0x100007081ec0: f2 f2 00 00 f2 f2 f8 f2 f8 f8 f8 f8 f8 f8 f8 f8
  0x100007081ed0: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x100007081ee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100007081ef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100007081f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==25224==ABORTING
FAIL test-airdecap-ng-0002.sh (exit status: 1)

FAIL: test-airdecap-ng-0003.sh
==============================

=================================================================
==25240==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc32f9bd10 at pc 0x000000528893 bp 0x7ffc32f9bbf0 sp 0x7ffc32f9bbe8
WRITE of size 8 at 0x7ffc32f9bd10 thread T0
    #0 0x528892 in c_avl_pick /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8
    #1 0x51493e in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:1056:9
    #2 0x7f2cc8a9a82f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #3 0x41a218 in _start (/home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng+0x41a218)

Address 0x7ffc32f9bd10 is located in stack of thread T0 at offset 240 in frame
    #0 0x5112ef in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:211

  This frame has 9 object(s):
    [32, 160) 'buf' (line 214)
    [192, 196) 'n' (line 217)
    [208, 214) 'bssid' (line 220)
    [240, 246) 'stmac' (line 220) <== Memory access at offset 240 partially overflows this variable
    [272, 280) 'st_cur' (line 223)
    [304, 328) 'pfh' (line 224)
    [368, 384) 'pkh' (line 225)
    [400, 404) 'option_index' (line 240)
    [416, 480) 'K' (line 852)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8 in c_avl_pick
Shadow bytes around the buggy address:
  0x1000065eb750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000065eb760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000065eb770: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000065eb780: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 00 00 00 00
  0x1000065eb790: 00 00 00 00 00 00 00 00 f2 f2 f2 f2 04 f2 06 f2
=>0x1000065eb7a0: f2 f2[06]f2 f2 f2 00 f2 f2 f2 00 00 00 f2 f2 f2
  0x1000065eb7b0: f2 f2 00 00 f2 f2 f8 f2 f8 f8 f8 f8 f8 f8 f8 f8
  0x1000065eb7c0: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000065eb7d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000065eb7e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000065eb7f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==25240==ABORTING
FAIL test-airdecap-ng-0003.sh (exit status: 1)

FAIL: test-airdecap-ng-0004.sh
==============================

=================================================================
==25262==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffe0991730 at pc 0x000000528893 bp 0x7fffe0991610 sp 0x7fffe0991608
WRITE of size 8 at 0x7fffe0991730 thread T0
    #0 0x528892 in c_avl_pick /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8
    #1 0x51493e in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:1056:9
    #2 0x7fd87a34382f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #3 0x41a218 in _start (/home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng+0x41a218)

Address 0x7fffe0991730 is located in stack of thread T0 at offset 240 in frame
    #0 0x5112ef in main /home/jbenden/Source/us.benden/aircrack-ng-git/src/airdecap-ng.c:211

  This frame has 9 object(s):
    [32, 160) 'buf' (line 214)
    [192, 196) 'n' (line 217)
    [208, 214) 'bssid' (line 220)
    [240, 246) 'stmac' (line 220) <== Memory access at offset 240 partially overflows this variable
    [272, 280) 'st_cur' (line 223)
    [304, 328) 'pfh' (line 224)
    [368, 384) 'pkh' (line 225)
    [400, 404) 'option_index' (line 240)
    [416, 480) 'K' (line 852)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/jbenden/Source/us.benden/aircrack-ng-git/src/aircrack-util/avl_tree.c:568:8 in c_avl_pick
Shadow bytes around the buggy address:
  0x10007c12a290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007c12a2a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007c12a2b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007c12a2c0: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 00
  0x10007c12a2d0: 00 00 00 00 00 00 00 00 00 00 00 00 f2 f2 f2 f2
=>0x10007c12a2e0: 04 f2 06 f2 f2 f2[06]f2 f2 f2 00 f2 f2 f2 00 00
  0x10007c12a2f0: 00 f2 f2 f2 f2 f2 00 00 f2 f2 f8 f2 f8 f8 f8 f8
  0x10007c12a300: f8 f8 f8 f8 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x10007c12a310: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007c12a320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007c12a330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==25262==ABORTING
FAIL test-airdecap-ng-0004.sh (exit status: 1)
```

You can reproduce this report by using Clang and enabling ASAN `configure` option.

Thanks,
-Joe

**Comment by ChrisLundquist** [comment]
Done in https://github.com/aircrack-ng/aircrack-ng/pull/1931

**Pull request merged**
