### PR TITLE
Support for clean builds with GCC 10.

### LINKED ISSUE #2138: Build failure with GCC 10
# Issue type

- Defect - Compilation or `make check` issue - Attach `config.log` and provide relevant system information such as `lscpu` - Make sure dependencies are installed

# System information

- OS: Fedora 32
- CPU: n/a

# Aircrack-ng version

- Version: 1.6
- Commit Revision hash: 1.6 git tag

# Defect
## How to reproduce the issue

Try to build aircrack-ng with GCC 10.0.1.

```c++
/bin/sh ./libtool  --tag=CC   --mode=link gcc -I/usr/include/libnl3  -Wall -O3 -std=gnu99 -fno-strict-aliasing -Wpointer-arith -Wstrict-overflow=2 -Wstrict-prototypes -fvisibility=hidden -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -release 1.6.0 -no-undefined -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o libaircrack-osdep.la -rpath /usr/lib64 lib/osdep/libaircrack_osdep_la-osdep.lo lib/osdep/libaircrack_osdep_la-network.lo lib/osdep/libaircrack_osdep_la-file.lo lib/osdep/libaircrack_osdep_la-linux.lo lib/osdep/libaircrack_osdep_la-linux_tap.lo lib/osdep/libaircrack_osdep_la-common.lo -lnl-3  -lnl-genl-3 libradiotap.la  -ldl -lm 
libtool: link: gcc -shared  -fPIC -DPIC  lib/osdep/.libs/libaircrack_osdep_la-osdep.o lib/osdep/.libs/libaircrack_osdep_la-network.o lib/osdep/.libs/libaircrack_osdep_la-file.o lib/osdep/.libs/libaircrack_osdep_la-linux.o lib/osdep/.libs/libaircrack_osdep_la-linux_tap.o lib/osdep/.libs/libaircrack_osdep_la-common.o  -Wl,--whole-archive ./.libs/libradiotap.a -Wl,--no-whole-archive  -lnl-3 -lnl-genl-3 -ldl -lm -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -O3 -fstack-protector-strong -O2 -g -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -Wl,-soname -Wl,libaircrack-osdep-1.6.0.so -o .libs/libaircrack-osdep-1.6.0.so
/usr/bin/ld: ./.libs/libradiotap.a(radiotap.o):/builddir/build/BUILD/aircrack-ng-1.6/lib/radiotap/radiotap.h:59: multiple definition of `__packed'; lib/osdep/.libs/libaircrack_osdep_la-linux.o:/builddir/build/BUILD/aircrack-ng-1.6/lib/radiotap/radiotap.h:59: first defined here
collect2: error: ld returned 1 exit status
```

Full build log attached.

[build.log](https://github.com/aircrack-ng/aircrack-ng/files/4439603/build.log)

### PR DESCRIPTION
**Pull request by jbenden**
This PR fixes the source code to compile cleanly on an x86-64 GCC10 compiler. It also fixes any source code warnings that were shown.

@Mister-X- On hold for a bit, need to run...

### CODE REVIEW

**Comment by jbenden** [comment]
@Mister-X- Would you mind reviewing this PR, for possible merge?

**Comment by Mister-X-** [comment]
Looks great.

Just one question, why removing Fortify? In 6f11718719ebc08e681816e8267756ece17887cb

**Comment by jbenden** [comment]
Thanks!

It was removed to fix macOS compilations (Travis CI). So this fact, along with most distributions choosing to enable this flag by default, led to a decision to just remove it - as opposed to excluding macOS.

Thoughts or a LGTM?

**Comment by jbenden** [comment]
@Mister-X- Thoughts or a vote for merge?

**Comment by neheb** [comment]
I hit this with OpenWrt as well as GCC10 is now available there.

**Comment by jbenden** [comment]
@neheb Did it compile without any warnings emitted? If not, please post the log. Thanks!

**Comment by neheb** [comment]
Well, I haven't tested this patchset. I only tried compiling aircrack-ng as is in the packages feed.

**Pull request merged**
