### PR TITLE
wpaclean: Do not crash on invalid prism2 pcap.

### LINKED ISSUE #1859: Segmentation Fault in wpaclean
Dear aircrack-ng team,

During my research, I have found a segmentation fault in your program
"wpaclean" in the aircrack-ng suite (version 1.2rc5,running on LinuxMint). I've attached the crashing input (it is contained in the zip folder): 
[wpaclean_crash.pcap.zip](https://github.com/aircrack-ng/aircrack-ng/files/1911540/wpaclean_crash.pcap.zip)
Find below the output of AddressSanitizer.

vincent@vincent ~/tmp/aircrack-ng $ ./src/wpaclean -nvr ../wpaclean_crash.pcap 
Pwning ../wpaclean_crash.pcap (1/1 100%)

ASAN:DEADLYSIGNAL

=================================================================
==27166==ERROR: AddressSanitizer: SEGV on unknown address 0x7fff36d19220 (pc 0x7f9bac1eac76 bp 0x7fff96d191d0 sp 0x7fff96d18968 T0)
    #0 0x7f9bac1eac75  (/lib/x86_64-linux-gnu/libc.so.6+0x14dc75)
    #1 0x4a2af4  (/home/vincent/tmp/aircrack-ng/src/wpaclean+0x4a2af4)
    #2 0x4f3e9f  (/home/vincent/tmp/aircrack-ng/src/wpaclean+0x4f3e9f)
    #3 0x4ea7b8  (/home/vincent/tmp/aircrack-ng/src/wpaclean+0x4ea7b8)
    #4 0x7f9bac0bd82f  (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #5 0x418cd8  (/home/vincent/tmp/aircrack-ng/src/wpaclean+0x418cd8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x14dc75) 
==27166==ABORTING

Best,
Vincent Ulitzsch

### PR DESCRIPTION
**Pull request by jbenden**
* Do not crash on an invalid prism 2 pcap file.
* Improved cross-platform support by using `le32_to_cpu`.
* Added unit-test for `wpaclean`.
* Fixes #1859

### CODE REVIEW

**Comment by aircrack-ng** [comment]
2 things:
- Not sure if on purpose but you change blank space in another condition
- Could you add a second test again wpa.pcap (in test/): https://github.com/aircrack-ng/aircrack-ng/blob/master/test/wpa.cap

**Comment by jbenden** [comment]
I've undone the formatting changes, with a reverse patch. It'll squash on merge to a simple and clean commit.

**Comment by ChunshengZhao** [comment]
1: Why (rc < 0) check again after assert(rc> = 0) ?
2: If "rc" is an invalid value, code has assert->Aborted, "off" is an invalid value **too**, code has return 0->Continue?

I think if the file with potential safety hazards, it is better to stop work immediately after verification.

**Comment by jbenden** [comment]
If assert does not catch it, it SEGV. Already shown, via the bug report. Asserts are stripped on non-development builds (ie: release builds or when `-DNDEBUG` is defined)

**Comment by jbenden** [comment]
Should the test (`if` statement) return a `-1` instead of `0`?

**Comment by ChunshengZhao** [comment]
If assert() is likely to fail, it should all be replaced. Found a problem, return  -1. Sorry my english.

**Pull request merged**
