### PR TITLE
update to clang-format-12

### LINKED ISSUE #2101: Use a more recent version for clang-format
An older version of clang, 3.9 was used for the `.clang-format` file. However, it is getting hard to come by, and migrating to a more recent version is ideal.

Version would most likely be v6 as it is the common denominator in a lot of distro.

Would need to check that it still matches formatting and adjust parameters if necessary.

### LINKED ISSUE #2132: Workflow problems caused by the code formatting checks in the build system
The build system currently uses an old version (v3.6 or v3.8) of clang for its code formatting verification.

These old versions of clang are not available in the current software repositories of distros (I'm referring to Fedora here, I have not checked others).  It seems a bit much to expect individuals wishing to contribute a PR to build old clang software from source on their workstations just to be able to run code formatting verification before submitting a PR.

Newer versions of clang are not compatible with v3.6/v3.8 (meaning that the code formatter uses different rules).

As a result, developers on current distros (again, Fedora in my case) cannot run code formatting verification locally on their workstation.

So we end up with a workflow loop of:

1. commit changes
2. push
3. submit PR
4. review code formatting failures reported by the build system
5. commit changes that only contain code formatting changes
6. push
7. go back to step 4

Examples of this can be seen in:

https://github.com/aircrack-ng/aircrack-ng/pull/2102
https://github.com/aircrack-ng/aircrack-ng/pull/2105

However, we also want to keep the git history as clean as possible, so the maintainers discourage commits that contain only code formatting changes.  The issue is that that would require either (a) changing git history that has already been pushed, or (b) require more work to rebase, etc., just for formatting changes, and even then, I don't _think_ (not 100% sure) we can rebase into the same branch that the github PR is pointing to (so would we also have to create a new PR in github for every code formatting commit?) 

My suggestion would be to use a different code formatting checker (that applies consistent rules over time), or relax the rules that are enforced so that the rules are simple and obvious to anyone just looking at other code in the codebase, and so only "obviously bad" formatting is caught by the build system.

Related:
https://github.com/aircrack-ng/aircrack-ng/issues/2101

### PR DESCRIPTION
**Pull request by gemesa**
Fixes #2101
Fixes #2132

Updated `clang-format-3.8`  to `clang-format-12.0`:
- `style.yml` and `clang_format_all.sh`: use `clang-format-12`
- `.clang-format`: removed [unnecessary](https://releases.llvm.org/12.0.0/tools/clang/docs/ClangFormatStyleOptions.html) single quotes + added missing newline to EOF
- `src/*`: updated source files by running `./build/clang_format_all.sh`

Main differences in the newly formatted source files:

Looks like the option `SpaceAfterCStyleCast` is not working properly with `clang-format-3.8` as there are some casts where the space is not inserted. This is solved with `clang-format-12`.

image

If statements are more compact with `clang-format-12`:

`clang-format-3.8`:
```
			if ((packet[z + 3] & 0x20) == 0 && opt.crypt == CRYPT_WEP
					&& !lopt.caffelatte
					&& !lopt.cf_attack)
```

`clang-format-12`:
```
			if ((packet[z + 3] & 0x20) == 0 && opt.crypt == CRYPT_WEP
					&& !lopt.caffelatte && !lopt.cf_attack)
```

Comments are indented properly with `clang-format-12`:

`clang-format-3.8`:
```
		}

// TODO: Get the speed from the packet if radiotap/prism header exist.

		printf("Retry bit: %d\n", _packet_elt_head->current->retry_bit);
```

`clang-format-12`:
```
		}

		// TODO: Get the speed from the packet if radiotap/prism header exist.

		printf("Retry bit: %d\n", _packet_elt_head->current->retry_bit);
```

I checked the following OSes to see if `clang-format-12` is available and installed it:

Ubuntu 18.04 (here the [install](https://askubuntu.com/questions/1409031/how-to-use-a-more-recent-clang-format-or-clang-tidy-version-on-ubuntu-18-04) is a bit more difficult but still manageable):
```
gemesa@gemesa-ubuntu:~$ uname -a
Linux gemesa-ubuntu 5.4.0-84-generic #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
gemesa@gemesa-ubuntu:~$ clang-format-12 --version
Ubuntu clang-format version 12.0.1-++20211102090516+fed41342a82f-1~exp1~20211102211019.11
```
Ubuntu 20.04:
```
gemesa@gemesa-ubuntu:~$ uname -a
Linux gemesa-ubuntu 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
gemesa@gemesa-ubuntu:~$ clang-format-12 --version
Ubuntu clang-format version 12.0.0-3ubuntu1~20.04.5
```
Ubuntu 22.04:
```
gemesa@ubuntu-pc:~$ uname -a
Linux ubuntu-pc 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
gemesa@ubuntu-pc:~$ clang-format-12 --version
Ubuntu clang-format version 12.0.1-19ubuntu3
```
Debian 11 (here the [install](https://stackoverflow.com/questions/66223241/how-to-install-clang-11-on-debian) is a bit more difficult but still manageable, buster has to be replaced with bullseye of course):
```
root@debian:/home/gemesa# uname -a
Linux debian 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
root@debian:/home/gemesa# clang-format-12 --version
Debian clang-format version 12.0.1-++20211027092659+fed41342a82f-1~exp1~20211027213207.7
```

Fedora 37 (my OS): `clang-format-12` not available. But I ran a test format with `clang-format-15` and there were no changes compared to version 12 so it can be used also as an alternative.
```
$ sudo dnf provides clang-format*
Last metadata expiration check: 1:15:42 ago on Sun 12 Mar 2023 09:59:20 PM CET.
clang-tools-extra-15.0.0-2.fc37.i686 : Extra tools for clang
Repo        : fedora
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.0-2.fc37.x86_64 : Extra tools for clang
Repo        : fedora
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.7-1.fc37.i686 : Extra tools for clang
Repo        : updates
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.7-1.fc37.x86_64 : Extra tools for clang
Repo        : @System
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.7-1.fc37.x86_64 : Extra tools for clang
Repo        : updates
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

```

CentOS 9: same as Fedora 37 but `clang-format-14` is also available.
```
# dnf provides clang-format*
Last metadata expiration check: 0:01:57 ago on Sun 12 Mar 2023 11:08:43 PM CET.
clang-tools-extra-14.0.0-1.el9.i686 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-14.0.0-1.el9.x86_64 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-14.0.5-1.el9.i686 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-14.0.5-1.el9.x86_64 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-14.0.6-1.el9.i686 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-14.0.6-1.el9.x86_64 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.1-2.el9.i686 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.1-2.el9.x86_64 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.7-2.el9.i686 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.7-2.el9.x86_64 : Extra tools for clang
Repo        : @System
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff

clang-tools-extra-15.0.7-2.el9.x86_64 : Extra tools for clang
Repo        : appstream
Matched from:
Filename    : /usr/bin/clang-format
Filename    : /usr/bin/clang-format-diff
```

### CODE REVIEW

**Comment by gemesa** [comment]
Did 2 test run also in my fork repo:
- https://github.com/gemesa/aircrack-ng/actions/runs/4399245293
- https://github.com/gemesa/aircrack-ng/actions/runs/4399267810

**Comment by Mister-X-** [comment]
A few notes:
- Ubuntu 18.04, I'm not worried as (normal) LTS support ends in a month of so.
- Debian buster is Debian 10. Debian 11 is bullseye (12 is going to be bookworm).
- LLVM provides distribution repos for different versions

**Comment by Mister-X-** [comment]
As an idea, for `clang_format_all.sh`, maybe we can add a range of Clang versions that work: I mean accepting anything between 12 and 15, which would remove the need to have 12 specifically, and be more future-proof (and possibly testing 16 to see if it's still the same result).

**Comment by gemesa** [comment]
> As an idea, for `clang_format_all.sh`, maybe we can add a range of Clang versions that work: I mean accepting anything between 12 and 15, which would remove the need to have 12 specifically, and be more future-proof (and possibly testing 16 to see if it's still the same result).

Good idea. I would prefer do it in an other PR because this one is already huge.

**Comment by Mister-X-** [comment]
A separate PR sounds good and actually makes sense as this one is just updating the clang version.

**Pull request merged**
